# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rdeploy_doc}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Dave Sieh}]
  s.date = %q{2011-12-09}
  s.description = %q{Tool for documenting deployment environments}
  s.email = %q{dave.sieh@nursinghomequality.com}
  s.executables = [%q{rdeploy_doc}, %q{rdeploy_doc}]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/rdeploy_doc",
    "lib/rdeploy_doc.rb",
    "lib/rdeploy_doc/directory_resource.rb",
    "lib/rdeploy_doc/file_resource.rb",
    "lib/rdeploy_doc/file_system_resource.rb",
    "lib/rdeploy_doc/link_resource.rb",
    "lib/rdeploy_doc/node_resource.rb",
    "lib/rdeploy_doc/package_resource.rb",
    "lib/rdeploy_doc/railtie.rb",
    "lib/rdeploy_doc/resource.rb",
    "lib/rdeploy_doc/service_resource.rb",
    "lib/rdeploy_doc/utils.rb",
    "spec/directory_resource_spec.rb",
    "spec/file_resource_spec.rb",
    "spec/file_system_resource_spec.rb",
    "spec/link_resource_spec.rb",
    "spec/package_resource_spec.rb",
    "spec/rdeploy_doc_spec.rb",
    "spec/resource_spec.rb",
    "spec/service_resource_spec.rb",
    "spec/spec_helper.rb",
    "spec/utils_spec.rb"
  ]
  s.homepage = %q{http://github.com/j0hnds/rdeploy_doc}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.6}
  s.summary = %q{Tool for documenting deployment environments}
  s.test_files = [
    "spec/directory_resource_spec.rb",
    "spec/file_resource_spec.rb",
    "spec/file_system_resource_spec.rb",
    "spec/link_resource_spec.rb",
    "spec/package_resource_spec.rb",
    "spec/rdeploy_doc_spec.rb",
    "spec/resource_spec.rb",
    "spec/service_resource_spec.rb",
    "spec/spec_helper.rb",
    "spec/utils_spec.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rspec>, [">= 2.6.0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rspec>, [">= 2.6.0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rspec>, [">= 2.6.0"])
  end
end

